name: PR Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Label PR based on description
      uses: actions-ecosystem/action-add-labels@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        labels: |
          Bug fix,bug
          New feature,enhancement
          Breaking change,breaking-change
